# Generated by Django 5.0.6 on 2024-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
