# Generated by Django 5.0.7 on 2024-11-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0019_category_remove_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
